### ISSUE TITLE
How I can change the key bit size of public key and secret key

### ISSUE THREAD

**Issue by MoBT** [JHUISI/charm#114]

**Comment by dennisschroer** [comment]
Of which scheme?

**Comment by MoBT** [comment]
For BSW07.
Thanks

**Comment by dennisschroer** [comment]
BSW07 is an Attribute Based Encryption scheme. The size of the keys depends on the used underlying (bilinear) pairing group, as the keys are based on elements of these groups. The framework contains multiple groups, while additional groups can be added. The default groups are defined [here](https://github.com/JHUISI/charm/blob/dev/charm/toolbox/pairingcurves.py#L71). The used group can be changed by passing another group on initialization.

**Comment by MoBT** [comment]
OK. So, I understand to change the size of bit key I need to use different pairing group. Thank you. It is really helpful. Appreciate @denniss17 .

**Comment by dennisschroer** [comment]
No problem. Can this issue be closed?
