### ISSUE TITLE
Charm for Android or ARM processor

### ISSUE THREAD

**Issue by MoBT** [JHUISI/charm#116]
HI, Is there any clear instructions to install charm on Android or IoT device (ARM processor , beaglebone, Rasperipy,. ) Thanks in advance

**Comment by dennisschroer** [comment]
I managed to install charm in the raspberry (model b2) by adding the cpu to configure.sh. After that, make and make install worked for me.  

https://github.com/denniss17/charm/commit/192b3db1746785f0b204d2a0f2b68e6e95d3fea5

**Comment by MoBT** [comment]
Thanks for the reply. Yes, I also comment "echo "Unsupported CPU = $cpu" ", and I can make and make install. but I don't know id that totally true or not.

**Comment by jakinyele** [comment]
I've updated the configure script. Thanks @denniss17 @MoBT!
