### ISSUE TITLE
KP-ABE scheme

### ISSUE THREAD

**Issue by MoBT** [JHUISI/charm#118]
Hi,

I was wondering if there is code for KP-ABE schemes for paper (Attribute-Based Encryption for Fine-Grained Access Control of Encrypted Data) author "Goyal" ? I tried to find it but I can't. Appreciate..

**Comment by dennisschroer** [comment]
There doesn't seem to be one currently, so if you really need it I'm afraid you have to implement it. Maybe you can contact Goyal?

**Comment by MoBT** [comment]
I see.. Thanks ...

**Comment by jakinyele** [comment]
It's quite straightforward to implement. Do you need pointers? Email me @ jakinye3@jhu.edu.

**Comment by MoBT** [comment]
@jakinyele , Thank you for the reply... Can I use the same setup code in BSW07 (CP-ABE) on KP-ABE ? because the setup CP-ABE (BSW07) and KP-ABE (by Goyal) seems same, both have no input for these algorithms.

**Comment by jakinyele** [comment]
A better scheme to start from is here: https://github.com/JHUISI/charm/blob/dev/charm/schemes/abenc/abenc_lsw08.py. I responded to your email.

**Comment by MoBT** [comment]
I saw that, thanks a lot  @jakinyele .. Appreciate.
