### ISSUE TITLE
Issue installing on MacOS

### ISSUE THREAD

**Issue by howardkitto** [JHUISI/charm#120]
I get

fatal error: 'gmp.h' file not found 

when installing Charm on MacOS Sierra 10.12

Here is the output, any ideas appreciated!

---

Howards-MBP:charm howardkitto$ brew install gmp
Warning: gmp-6.1.1 already installed
Howards-MBP:charm howardkitto$ brew install pbc
Warning: pbc-0.5.14 already installed
Howards-MBP:charm howardkitto$ brew install openssl
Warning: openssl-1.0.2j already installed
Howards-MBP:charm howardkitto$ ./configure.sh --enable-darwin
Install prefix    /usr/local
data directory    /usr/local/share/charm
binary directory  /usr/local/bin
library directory /usr/local/lib
config directory  /usr/local/etc
Source path       /Users/howardkitto/Projects/sovrin/charm
CFLAGS            -O2 -g 
CHARM_CFLAGS       -m64 -Wall -Wundef -Wwrite-strings -Wmissing-prototypes  -fstack-protector-all -Wendif-labels -Wmissing-include-dirs -Wempty-body -Wnested-externs -Wformat-security -Wformat-y2k -Winit-self -Wignored-qualifiers -Wold-style-definition -Wtype-limits
LDFLAGS           -m64 
make              make
python            /Library/Frameworks/Python.framework/Versions/3.5/bin/python3
python-config     /Library/Frameworks/Python.framework/Versions/3.5/bin/python3-config
build_ext options build_ext 
install           install
host CPU          x86_64
wget              /usr/local/bin/wget
gprof enabled     no
profiler          no
static build      no
-Werror enabled   no
integer module    yes
ecc module        yes
pairing module    yes
disable benchmark no
libm found        yes
libgmp found      no
libpbc found      no
libcrypto found   no
Documentation     no
Howards-MBP:charm howardkitto$ make install
/Library/Frameworks/Python.framework/Versions/3.5/bin/python3 setup.py install
Platform: Darwin
Config file: /Users/howardkitto/Projects/sovrin/charm/config.mk
running install
running bdist_egg
running egg_info
writing Charm_Crypto.egg-info/PKG-INFO
writing dependency_links to Charm_Crypto.egg-info/dependency_links.txt
writing requirements to Charm_Crypto.egg-info/requires.txt
writing top-level names to Charm_Crypto.egg-info/top_level.txt
package init file 'charm/schemes/prenc/**init**.py' not found (or not a regular file)
reading manifest file 'Charm_Crypto.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'README'
writing manifest file 'Charm_Crypto.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.6-intel/egg
running install_lib
running build_py
copying charm/config.py -> build/lib.macosx-10.6-intel-3.5/charm
running build_ext
building 'charm.core.math.pairing' extension
/usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -DBENCHMARK_ENABLED=1 -Icharm/core/utilities/ -Icharm/core/benchmark/ -I/Library/Frameworks/Python.framework/Versions/3.5/include/python3.5m -c charm/core/math/pairing/pairingmodule.c -o build/temp.macosx-10.6-intel-3.5/charm/core/math/pairing/pairingmodule.o
In file included from charm/core/math/pairing/pairingmodule.c:30:
charm/core/math/pairing/pairingmodule.h:37:10: fatal error: 'gmp.h' file not found
# include <gmp.h>

```
     ^
```

1 error generated.
error: command '/usr/bin/clang' failed with exit status 1
make: **\* [install] Error 1

**Comment by sza-1** [comment]
@howardkitto thank you for reporting the issue. Could you show `clang -E - -v < /dev/null` output?

**Comment by sza-1** [comment]
@howardkitto looks like you forgot to install Xcode Command Line Tools (https://github.com/Homebrew/brew/blob/master/docs/Installation.md) which is required for newer versions of Homebrew. Please run `xcode-select --install` then `./configure.sh --enable-darwin` again and let me know if it works for you.

**Comment by howardkitto** [comment]
@crazyh Problem solved, I installed the Xcode Command Line Tools and it installed no problem. Thanks so much!
