### ISSUE TITLE
Abenc User Input

### ISSUE THREAD

**Issue by raselc** [JHUISI/charm#128]
Hi,
Is there any way to use user input in abenc_bsw07 and abenc_lsw08 instead of random number generation in this two schemes.

Thank you in advance for your cooperation.

**Comment by jakinyele** [comment]
Yes, using hybrid encryption. See the [charm adapters for ABE].(https://github.com/JHUISI/charm/blob/dev/charm/adapters/abenc_adapt_hybrid.py).
