### ISSUE TITLE
Benchmark Error

### ISSUE THREAD

**Issue by chisomiloks** [JHUISI/charm#129]
Just installed charm-crypto and when I try to run any of the ABE source codes I get this error

ImportError: No module named benchmark

Any idea how to solve this?

**Comment by yuanma7** [comment]
Hi! I meet this question, could you please tell me how to solve it? Thank you!

**Comment by chisomiloks** [comment]
I cannot remember exactly what my problem was but I think it had to do with what version of python I was using in my app vs what version of python I had installed charm for.

If you could provide additional information I may be able to be of more help
