### ISSUE TITLE
all test failed on mac osx 10.9.5 and archlinux

### ISSUE THREAD

**Issue by angry-bird** [JHUISI/charm#133]
After charm installed without error, i run into test errors like this:
![screen shot 2017-03-10 at 12 27 45 pm](https://cloud.githubusercontent.com/assets/7440892/23782428/78959c1e-058f-11e7-9b2b-498a049b7eec.png)
![screen shot 2017-03-10 at 12 29 08 pm](https://cloud.githubusercontent.com/assets/7440892/23782429/7c0142e0-058f-11e7-9683-bb03564a694d.png)
Any help

**Comment by jakinyele** [comment]
Can you try with python 3.5?

**Comment by angry-bird** [comment]
@jakinyele Thanks a lot.
I brew uninstall python3.6.0, install python 3.5.2 with pyenv, now all tests passed!
