### ISSUE TITLE
Decrypt and Encrypt data in Android application (java code)

### ISSUE THREAD

**Issue by MahdiELARBI** [JHUISI/charm#134]
Hello,

I’m getting an Encrypted data with "Charm" form sever and i want to Decrypt it in my Android application using java code.

What can i do ? i dont find a charm lib that support android !

Please, if you have any idea can you give me a tutorial !

Thank you very much !

**Comment by jakinyele** [comment]
We don't have a JNI port for Charm. Perhaps, https://github.com/kuri65536/python-for-android might help?

**Comment by MahdiELARBI** [comment]
thank you for your response, this link can help to run a python build in android device, but i want to decrypt and encrypt data in my android application, i want to add the encryption code throw my java code.

**Comment by jakinyele** [comment]
Charm is python only and does not support Java. You could try writing some Java glue code around the python-for-android stuff. However, keep in mind there are other crypto libs that do provide Java ports. For example, https://github.com/ArteMisc/libstodium.
