### ISSUE TITLE
Fail to install charm using pip3 on Mac

### ISSUE THREAD

**Issue by ringsaturn** [JHUISI/charm#144]
I fail to install Charm using pip3 like this:

```bash
$ pip3 install charm
Collecting charm
  Using cached charm-1.0b4.zip
Collecting BeautifulSoup (from charm)
  Using cached BeautifulSoup-3.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/1y/df36z75s7rz7fl4y2ctn250w0000gq/T/pip-build-mkejymon/BeautifulSoup/setup.py", line 22
        print "Unit tests have failed!"
                                      ^
    SyntaxError: Missing parentheses in call to 'print'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/1y/df36z75s7rz7fl4y2ctn250w0000gq/T/pip-build-mkejymon/BeautifulSoup/
```

I also try to install Charm under Python2.7 on Windows, however it returns the same error.

Anyone knows what resulted this?

**Comment by 1phan** [comment]
>         print "Unit tests have failed!"
                                      ^
    SyntaxError: Missing parentheses in call to 'print'

this is a python2 version I guess, in python3 call  print() without "()" is illegal

\---------------------------------------------------------------------------------------------------------------------

I'm sorry I made a mistake, I describe this error in this [issue](https://github.com/JHUISI/charm/issues/153)

**Comment by jakinyele** [comment]
Looks like you tried to install a different project. Try pip3 install charm-crypto instead. However, charm-crypto currently cannot be installed via pip3 on some platforms yet.
