### ISSUE TITLE
BSW07, error in encryption fucntion 

### ISSUE THREAD

**Issue by MoBT** [JHUISI/charm#148]
Hi,
I am using integer group in BSW07 scheme instead of pairing. setup, and keygen function are working well but I have problem in encryption function on the the line that call " shares = util.calculateSharesDict(s, policy) ". Is anyone have idea what I have to do here to fix my problem ? 

Thank you

**Comment by jakinyele** [comment]
BSW07 only works with pairing groups.

**Comment by MoBT** [comment]
Is there ABE scheme work with  integer group  ?

**Comment by jakinyele** [comment]
Not that I am aware of. The constructions I know of are either pairing or lattice-based. Charm doesn't support lattice based crypto though.
