### ISSUE TITLE
YCT14

### ISSUE THREAD

**Issue by MoBT** [JHUISI/charm#149]
How come yct scheme setting is no pairing and inside the code they used pairing ?

**Comment by jakinyele** [comment]
Can you provide a link to the paper?

**Comment by MoBT** [comment]
The paper is : A lightweight attribute-based encryption scheme for the Internet of things, you can find it here : http://ac.els-cdn.com/S0167739X14002039/1-s2.0-S0167739X14002039-main.pdf?_tid=0e20041e-8aa5-11e7-bc8b-00000aacb35d&acdnat=1503782897_d56ee2b07c3b4c9fbb74b732cf019fdf . 
in charm it in scheme folder called abenc_yct14.py .
Thank you

**Comment by MoBT** [comment]
@jakinyele is there update please ?

**Comment by jakinyele** [comment]
My best guess is that "No pairing" refers to the fact that the scheme is designed without pairing computations. I'd recommend that you direct your question to the author (@artjomb) since he is more familiar with this work. All the best.

**Comment by artjomb** [comment]
@MoBT The implementation only uses an elliptic curve group that is pairing friendly, but it doesn't actually use a pairing (only elements of G1 are used and not G2). There is not a single reference to `charm.toolbox.pairinggroup.pair`. You can implement it with any other elliptic curve group (probably needs to be a prime order group) or even integer group.

**Comment by MoBT** [comment]
@jakinyele @artjomb Thank you.
