### ISSUE TITLE
error because of bs3?

### ISSUE THREAD

**Issue by 1phan** [JHUISI/charm#153]
I think charm include beautifulsoup3, for this error:

> ~ » pip install charm
> Collecting charm
>   Using cached charm-1.0b4.zip
> Collecting **BeautifulSoup** (from charm)
>   Using cached BeautifulSoup-3.2.1.tar.gz
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-build-ji1j9x3v/BeautifulSoup/setup.py", line 22
>         print "Unit tests have failed!"
>                                       ^
>     SyntaxError: Missing parentheses in call to 'print'
>     
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ji1j9x3v/BeautifulSoup/
> 

There's something error in install beautifulSoap in python3 by pip3.

[document](https://www.crummy.com/software/BeautifulSoup/bs4/doc/) of beautifulSoup:

> You might be looking for the documentation for Beautiful Soup 3. If so, you should know that **Beautiful Soup 3 is no longer being developed**, and that Beautiful Soup 4 is recommended for all new projects.

> (The **BeautifulSoup** package is probably **not what you want.** That’s the previous major release, **Beautiful Soup 3.** Lots of software uses BS3, so it’s still available, but if you’re writing new code you should install beautifulsoup4.)
> 
> If you don’t have easy_install or pip installed, you can download the Beautiful Soup 4 source tarball and install it with setup.py.

May be we should move on to bs4?  I found this one in bs3's [document](https://www.crummy.com/software/BeautifulSoup/#Download/)

**> Beautiful Soup 3 works only under Python 2.x.** It is licensed under the same license as Python itself.

**Comment by jakinyele** [comment]
Wrong project.
