### ISSUE TITLE
how can I enable the s390/s390x support ?

### ISSUE THREAD

**Issue by nobody4t** [JHUISI/charm#162]
I need this run on s390 machine, how can I enable it?

As I found that if I change the configure.sh directly, this can run normally. But not sure if it is good.

**Comment by nobody4t** [comment]
I run the test cases and all of them passed. So I guess this also support s390?

**Comment by nobody4t** [comment]
@jakinyele So if it does support s390, please change the file and push the commit. Would you please?

**Comment by jakinyele** [comment]
What needs to change in configure? If you submit a PR, i'll merge and it'll be done with. Thanks @WandyLau!
