### ISSUE TITLE
Can't find the implemntation of BBS04

### ISSUE THREAD

**Issue by Hezaveh** [JHUISI/charm#192]
In your paper, you mentioned a listing of the cryptographic schemes that you implemented and BBS04 [18] is one of them. but I can't find it in your [Python Module Index](https://jhuisi.github.io/charm/py-modindex.html).

Do you know another resource that I could find the implementation of BBS04 [18]?

18. Boneh, D., Boyen, X., and Shacham, H. Short group signatures. In CRYPTO (2004), vol. 3152 of LNCS, pp. 45–55.

**Comment by jakinyele** [comment]
Here: https://github.com/JHUISI/charm/blob/aded57440f23a9a75d7f09ee1d6d0392bed7b39f/charm/schemes/grpsig/groupsig_bgls04.py
