### ISSUE TITLE
Trivial hash collisions for tuples

### ISSUE THREAD

**Issue by timothymctim** [JHUISI/charm#201]
The [EC hashing function](https://github.com/JHUISI/charm/blob/29590c025c12f068c89e6a95dfd38b43b4f7dd63/charm/toolbox/ecgroup.py#L65-L79) has trivial hash collisions. Each tuple element is just concatenated to the a byte string, meaning that–for example–`hash(('ab', 'c'))` is the same as `hash(('a', 'bc'))`. Depending on the security model, this is a problem.

I believe that *either* this isn’t a vulnerability and should be properly documented, *or* this is a weakness that should be addressed. To address this, one could for example think of `base64` encoding the tuple elements and then joining the resulting elements with a character not in the `base64` alphabet, e.g., `|`.

**Comment by timothymctim** [comment]
I’m sorry to say that I believe the code change didn’t properly address the issue.
In this updated code `hash(('a|', 'b'))` still collides with `hash(('a', '|b'))`.

**Comment by jakinyele** [comment]
Please submit a PR with a better fix @timothymctim. Thanks!
