### ISSUE TITLE
Can't add custom message to blindly sign with protocol_a01

### ISSUE THREAD

**Issue by oscar-king** [JHUISI/charm#228]
In the protocol the message that is blindly signed seems to be hard-coded into the methods:
```python
epsilon = self.group.hash(zeta, zeta1, alpha, beta1, beta2, eta, "msg")
```
and 
```python
p2 = self.group.hash(zeta, zeta1, tmp1, tmp2, tmp3, tmp4, "msg")  
```

**Comment by jakinyele** [comment]
@oscar-king Could extend the protocol impl to include the input message via a command-line flag? I guess there are different ways to support custom messages. Feel free to submit a PR. Thanks!

**Comment by oscar-king** [comment]
@jakinyele True. Thanks for the reply!
