### ISSUE TITLE
Source of randomness on Windows

### ISSUE THREAD

**Issue by jakinyele** [JHUISI/charm#23]
Currently, the pairing module defaults to a deterministic PRNG since there is no /dev/urandom on Windows. Need to pull from the appropriate source of entropy for Win systems.

**Comment by imichaelmiers** [comment]
I thought we had decided all randomness was from openssl

**Comment by jakinyele** [comment]
Mike figured out the issue in the PBC configure script, fixed it and issuing a patch upstream
