### ISSUE TITLE
Problem occurred when 'make install'

### ISSUE THREAD

**Issue by Billy1900** [JHUISI/charm#232]
when I install charm by tab <code>make install</code>, the problem will occur.
the error message as below:
<pre>
ImportError: module 'setuptools.dist' has no attribute 'check_specifier'
Makefile:43: recipe for target 'install' failed
make: *** [install] Error 1
</pre>

How can I get through the problem and install it successfully?

**Comment by jakinyele** [comment]
what OS and version of python 3.x? @Billy1900

**Comment by Billy1900** [comment]
it is weird when I install it on Mac, it works well. But when I install on my linux with the same operation, even the same version of openssl, gmp, pbc, the error still occurred.
OS: Ubuntu 16.04
python 3.5

**Comment by Billy1900** [comment]
when I use python 3.7, it succeeds!
