### ISSUE TITLE
Installing charm-dev on Ubuntu python3.8 HELP!

### ISSUE THREAD

**Issue by Rabieh07** [JHUISI/charm#260]
Iam trying to compile charm-dev on Ubuntu using python 3.8. After I did sudo make install, I cannot run benchmark_test.py. The problem seems to me in charm.core.math.integer. The following is exactly the error I have,. Any help is appreciated 

username@ubuntu:~/charm/charm-dev/charm/test/benchmark$ python3 benchmark_test.py 
ERROR: module load failed!
Traceback (most recent call last):
  File "benchmark_test.py", line 4, in <module>
    from charm.core.math.integer import * 
SystemError: initialization of integer failed without raising an exception

**Comment by nikosft** [comment]
Try running `sudo ldconfig` after finishing the installation.

**Comment by lrusso96** [comment]
@nikosft @Rabieh07 I had a similar issue and I had to downgrade to Python 3.7.

**Comment by terry-fee** [comment]
Looks like Python 3.8 and above does not like the arguments of a C extension function to be declared as `METH_O | METH_NOARGS` in _integermodule.c_. This ultimately caused the initialisation of the Python object to fail silently and without error messages.

I have created a pull request for this.
