### ISSUE TITLE
Not able to hash group element to binary string. Help!!

### ISSUE THREAD

**Issue by ashishlakraa** [JHUISI/charm#278]
I want to have a cryptographic hash function with the mapping as _H: G2 → {0, 1}<sup>n</sup> for some n_ . But in charm-crypto we can only hash an element type/string to a specific field only.

I am implementing an algorithm for certificateless public encryption with keyword search and in the algorithm I need this hash function.

Can someone please help me how to facilitate this hash function _H_ functionality in charm?

**Comment by lrusso96** [comment]
@ashishlakra01 you could do something like this:

```python
from hashlib import sha256

group = ... # some PairingGroup
g2 = ... # element of G2
digest = sha256(group.serialize(g2)).digest()
```

**Comment by ashishlakraa** [comment]
> @ashishlakra01 you could do something like this:
> 
> ```python
> from hashlib import sha256
> 
> group = ... # some PairingGroup
> g2 = ... # element of G2
> digest = sha256(group.serialize(g2)).digest()
> ```

Thank you so much @lrusso96 I will try this out.
