### ISSUE TITLE
initialization of interger failed without raising an exception

### ISSUE THREAD

**Issue by kitescat** [JHUISI/charm#287]
In charm/toolbox/conversion.py 
Line3:
         from charm.core.math.interger import interger 
why came out an error:**initialization of interger failed** ?
Im using Charm-Crypto 0.5,py3.8,testing **yct_14** on ubuntu 18.
Could anyone who knows about it contact me asap?Thanks!

**Comment by PekeDevil** [comment]
I also was unable to implement anything using YCT_14.

However, YCT14 is a broken scheme, if possible you should choose a different one. One of the researchers that found the vulnerability in YCT14 explains it [here](https://github.com/JHUISI/charm/issues/276#issue-949741135).

That being said, [in this issue](https://github.com/JHUISI/charm/issues/239) some suggest that downgrading Python may solve some of the problems with integers on this scheme.

Besides, AC17 and YCT14 apparently [have some issues with serialization](https://github.com/JHUISI/charm/issues/227).

So yeah, you should avoid using that scheme. However, if you cannot, I hope the above issues help.

**Comment by kitescat** [comment]
Thx！I didn’t expect to get replay such soon.
1. I did notice that YCT14 is a broken scheme.So now im using the BSW07 as my schema.
2. Any other better schema for an encryption function? Seems that some schemas implemented in Charm has been proved that they are unsafe. This's the top one topic that im concerned now.

**Comment by PekeDevil** [comment]
Actually, following Monday I'm presenting a paper about a survey of ABE libraries and [you can read it here.](https://www.researchgate.net/publication/363098622_All_Cryptolibraries_Are_Beautiful_But_Some_Are_More_Beautiful_Than_Others_A_Survey_of_CP-ABE_Libraries) Although I only provide experimental results for a few CP-ABE schemes, I think that the Tables will be useful to you. I'm working on an expanded version in which I implement ALL the schemes from four different libraries in an RPI0 and an RPI4. This one, however, is still being revised by my advisors 😄

UPDATE: The Expanded Survey [is here!](https://www.researchgate.net/publication/363858843_Too_Many_Options_A_Survey_of_ABE_Libraries_for_Developers)

Still, so far my finding are:

- Charm's fastest scheme for encryption is [LSW10 ](https://ieeexplore.ieee.org/document/5504791)(a KP-ABE scheme) -->[ Here you have it on Charm](https://jhuisi.github.io/charm/charm/schemes/abenc/abenc_lsw08.html)
- Charm's fastest scheme for decryption is BSW07
- If you  need a CP-ABE scheme in Charm, YAHK14 and FAME seem good options too

However, if you need an even fastest scheme for encryption, you should implement [OpenABE's](https://github.com/zeutro/openabe) W11. Bear in mind, however, that this scheme is slower on decryption.

From the point of view of pure security (aka the maths behind the algorithms), I think [this paper by Marloes Venema and Greg Alpar will help you](https://eprint.iacr.org/2020/460). They even have [another paper](https://eprint.iacr.org/2022/038) in which they study and discuss the mathematical efficiency of various algorithms.

Both of the above papers have a GitHub repo: 

- [ABE Squared](https://github.com/abecryptools/abe_squared)
- [ABE attacks](https://github.com/kudelskisecurity/abeattacks)

**Comment by kitescat** [comment]
Thx for answering my questions with these details!
My research intrests include **blockchain and cryptography**.Recently i've been working on experiments about Decentralizing [Kerberos](https://web.mit.edu/kerberos/)(which is a traditional schema about intra-domain authentication in Computer systems).

I've read your paper about the survey of ABE libraries and other articles you've published.Really appreciate your work!
- Seems that using python with Charm for my paper's experimental parts is a good idea,since i saw that the effiency and cost 
are affordable than the other libararies through your article.
- Also,I think it would be a good idea to try the LSW10 and FAME later in my schema.
- As for security,the mentioned paper is helpful for the security analysis of my schema.

Thx again!Hope your paper will be published smoothly！

**Comment by PekeDevil** [comment]
I'm glad it was of help! If you're working with Blockchain, ABE and access control, [Damiano Di Francesco Maesa](https://www.researchgate.net/profile/Damiano-Maesa) may be interesting for you. Last time I checked, he had three papers with Blockchain, Access control and attribute management.

Wish you the best of lucks with your research!
