### ISSUE TITLE
Charm integers mix badly with Python integers

### ISSUE THREAD

**Issue by nikitaborisov** [JHUISI/charm#46]
The integer routines in charm.core.math.integer give wrong results when combined with Python integers. I would expect y and z to have the same value as w, but z loses the modulus, whereas y actually swaps the operands to mod:

``` python
ubuntu% python3
Python 3.2.3 (default, Oct 19 2012, 20:13:42) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import charm.core.math.integer as chint
>>> x = chint.integer(12345678)
>>> x
12345678
>>> y = 100 % x
>>> y
78 mod 100
>>> z = chint.integer(100,x)
>>> z
100
>>> w = chint.integer(100,int(x))
>>> w
100 mod 12345678
```

There are a few other bugs I have run into; might it make more sense to use the gmpy/gmpy2 libraries (http://code.google.com/p/gmpy/) instead in Charm?

(Note: I haven't used them myself but they seem a bit cleaner than Charm's version, if only by virtue of having documentation.)

**Comment by jakinyele** [comment]
Fixing the bugs now. What other issues have you found? Thanks!

**Comment by nikitaborisov** [comment]
Great, thanks!  Here another one I ran into:

``` python
>>> import charm.core.math.integer as chint
>>> x = chint.integer(33,101)
>>> x
33 mod 101
>>> 1/x
zsh: segmentation fault (core dumped)  python3
```

And this one is perhaps not incorrect but unexpected:

``` python
>>> x = chint.integer(33,101)
>>> y = chint.integer(49,101)
>>> x*y
1617 mod 101
```

**Comment by jakinyele** [comment]
Will fix these too and will add more documentation to the module. Thanks!

**Comment by nikitaborisov** [comment]
Thanks, that fixes "100 % x". 

I still get a missing base if I do integer(100,x) and a core dump for 1/x. Do you want me to open separate issues for those?

**Comment by jakinyele** [comment]
I'm about to check in fixes for the other bugs. But yes, pls create a separate issue and i can close it with my next commit. Thanks!

**Comment by nikitaborisov** [comment]
OK, I created #48 and #49

**Comment by jakinyele** [comment]
Thanks...more fixes coming up.
