### ISSUE TITLE
Pyparsing and delimiting characters

### ISSUE THREAD

**Issue by gdbelvin** [JHUISI/charm#5]
Pyparsing crashes when the policy string contains attributes that have delimiting characters.
For example, the policy string (JHU_Professor AND JHMI_Staff) will cause pyparsing to crash. 

Allowing delimiting characters in the policy string will be important in the muti authority setting of Attribute Based Encryption since each attribute must be unique. ie. it is important to distinguish what JHU calls "staff" and what JHMI calls "staff".

**Comment by jakinyele** [comment]
I'll update the parser grammar to allow '_' in the attribute. Thanks!!
