### ISSUE TITLE
Intuition around the integer class

### ISSUE THREAD

**Issue by diedthreetimes** [JHUISI/charm#50]
I find it a bit confusing the way the integer handles initial negative values.

To me it seems like integer(-3, 10000) would either error, or return the modular inverse of 3. 
I would also expect integer(3) \* -1 have similar behavior.

Instead we see behavior like
    integer(3, 10000) \* -1 #=> 55340232221128654845 mod 10000
    integer(3) \* -1 #=> 55340232221128654845

Upon inspection it makes perfect sense that this does not compute the intended result, but it can lead to hard to track down bugs.

I propose that if a negative number is applied to an integer (or a modular integer) an error or warning is displayed to the user.

Thanks for all the hard work,

Sky

**Comment by jakinyele** [comment]
Good catch. Fix coming soon. Thanks!

**Comment by diedthreetimes** [comment]
Perhaps I should open another issue, but i thought I would point out another quick (low priority) oddity. There doesn't seem to be any easy way to access the modulus of an integer directly from python. I would expect something like `integer(3, 100).m` to return 100, but I can't seem to find the appropriate method. Such a method may exist and I'm just missing it.

**Comment by jakinyele** [comment]
It doesn't exist but we can add it. Pls, open another issue so we can close it on the next commit.
