### ISSUE TITLE
Calling reduce on an integer with no modulus crashes python.

### ISSUE THREAD

**Issue by diedthreetimes** [JHUISI/charm#51]
```
from charm.core.math.integer import integer
s = integer(35)
s.reduce()
```

The output is the c error 'Floating point exception: 8' and python crashes.

**Comment by jakinyele** [comment]
This has been fixed in the charm-dev branch. We will produce v0.43 sometime soon (by the end of the month hopefully), but feel free to test against the dev version in the meantime. Thanks!

**Comment by diedthreetimes** [comment]
Thanks a lot, will do.
