### ISSUE TITLE
Multiple imports of IntegerGroup crashes python [dev]

### ISSUE THREAD

**Issue by diedthreetimes** [JHUISI/charm#53]
The following causes a seg fault on the dev branch.

```
from charm.toolbox.integergroup import IntegerGroup
from charm.toolbox.integergroup import IntegerGroup
```

**Comment by jakinyele** [comment]
I think this has been fixed. Perhaps, can you re-test with the latest dev head to confirm on your end? Thanks!

**Comment by diedthreetimes** [comment]
Fixed, thanks!
