### ISSUE TITLE
ECGroup.hash() ignores tuples of bytes() objects

### ISSUE THREAD

**Issue by andres-erbsen** [JHUISI/charm#58]
```
from charm.toolbox.ecgroup import ECGroup
from charm.toolbox.eccurve import secp256k1
group = ECGroup(secp256k1)
group.hash((b'',)) == group.hash((b'fish',b'X',b'a')) # => True
```

This shouldn't e the desired behaviour - a hash function should either try to behave like a random oracle or throw an exception if it is unable to.
Arch Linux, Python 3.3.2, charm built from git today.

**Comment by jakinyele** [comment]
Fixed in dev branch
