### ISSUE TITLE
ECGroup.hash() does not use full range, return small numbers

### ISSUE THREAD

**Issue by andres-erbsen** [JHUISI/charm#66]
```
>>> from charm.toolbox.ecgroup import ECGroup
>>> from charm.toolbox.PKSig import PKSig
>>> from charm.toolbox.eccurve import secp256k1
>>> from os import urandom
>>> group = ECGroup(secp256k1)
>>> sum(int(repr(group.hash(urandom(32)))) for i in range(10000)) / sum(int(repr(group.random())) for i in range(10000))
1.265072095935034e-29
```

OpenSSL 1.0.1e 11 Feb 2013
[GCC 4.8.0 20130502 (prerelease)] on linux x86_64
Python 3.3.2 (default, May 21 2013, 15:40:45)
current dev branch built using https://aur.archlinux.org/packages/py/python-charm-git/PKGBUILD

**Comment by andres-erbsen** [comment]
`ecmodule.c` line 1222 (and 1232) gets only `HASH_LEN=20` bytes, which is not enough for curves with more than 160 bits. It should probably look at the curve element size instead.

**Comment by jakinyele** [comment]
That is correct. We currently use SHA-1 but now switching to SHA-2 for starters, then applying a variable-size hashing technique to get the desired bit size for the given curve. Will be fixed soon. Thanks.
