### ISSUE TITLE
Exponentiation Segmentation Fault

### ISSUE THREAD

**Issue by gdbelvin** [JHUISI/charm#7]
With traditional python objects, exponentiations on unsupported objects throws an error eg:

```
>>> b=b'test'
>>> b ** 3
Traceback (most recent call last):
 File "<input>", line 1, in <module>
 TypeError: unsupported operand type(s) for ** or pow(): 'bytes' and 'int'
```

However, when this is done with an element object, a segmentation fault is thrown. 
Type checking is needed in order to avoid segmentation faults

```
>>> from charm.integer import *
>>> rand = init()
>>> p = rand.randomPrime(1024)
>>> b'test' ** p
Segmentation fault
```

**Comment by gdbelvin** [comment]
This also fails when raising integers to element objects

```
>>> from charm.integer import *
>>> rand = init()
>>> p = rand.randomPrime(1024)
>>> 123 ** p
Segmentation fault
```

**Comment by jakinyele** [comment]
Bug fixed in latest revision r115
