### ISSUE TITLE
Type casting EC points from str to <class pairing.Element> 

### ISSUE THREAD

**Issue by prasanththandra** [JHUISI/charm#82]
I was implementing a sample code  and face the following problem. 
P = P1 *\* k  gave error like left hand operand is not suitable, the issue is I have red the point P1 from a file. When I checked  type(P1) it is showing str where as the points like P2=group.rand(G1) shows <class pairing.Element>  when used with type.

Can any one help how i can convert the point from file to required type

**Comment by Billy1900** [comment]
I also met this problem, could anyone tell me which API can help me convert the type?
