### ISSUE TITLE
fix needing --python=

### ISSUE THREAD

**Issue by imichaelmiers** [JHUISI/charm#9]
Really the system should try to build and install for pythong 2\* and 3 if possible and fall back to whichover one is present and warn on the other

**Comment by jakinyele** [comment]
Agreed. Python 3 should be the first thing we look for, then fall back to python 2.7 otherwise complain to user. Sound good?

**Comment by imichaelmiers** [comment]
don't fall back. Just assume python3 for the python3 branch

**Comment by imichaelmiers** [comment]
Not sure when this was fixed but it was
